name: Build Tarantool

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tarantool and tt
        run: |
          curl -L https://tarantool.io/release/3/installer.sh | sudo bash
          sudo apt install -y tt tarantool tarantool-dev
          tt version
      - uses: actions/checkout@v4
      - name: Build tarantool/deque
        run: make -C tarantool/deque build
      - name: Pack tarantool/deque
        run: make -C tarantool/deque pack
      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: deque
          path: tarantool/deque/*.deb
