# yaml-language-server: $schema=https://gist.githubusercontent.com/ochaton/24957db1617df119b30b5e7cec05e3cf/raw/cf498e23928eefad2cf31748a369a8fa124166f2/config.schema-3.3.0.json
credentials:
  users:
    python:
      password: python
      privileges:
        - universe: true
          permissions: ["read", "write", "execute"]

app:
  module: 'storage'

groups:
  storages:
    replicasets:
      deque001:
        instances:
          deque_001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
